# Gazebo API Contracts for Digital Twin Simulation

openapi: 3.0.0
info:
  title: Gazebo Simulation API
  version: 1.0.0
  description: API for controlling and monitoring Gazebo physics simulations
  contact:
    name: Simulation Team
    email: simulation@digital-twin.edu

paths:
  /worlds/{world_name}/physics:
    get:
      summary: Get physics properties of a simulation world
      parameters:
        - name: world_name
          in: path
          required: true
          schema:
            type: string
          description: Name of the simulation world
      responses:
        '200':
          description: Physics properties retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhysicsProperties'
        '404':
          description: World not found
    patch:
      summary: Update physics properties of a simulation world
      parameters:
        - name: world_name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhysicsPropertiesUpdate'
      responses:
        '200':
          description: Physics properties updated successfully
        '400':
          description: Invalid physics parameters
        '404':
          description: World not found

  /worlds/{world_name}/models/{model_name}/sensors:
    get:
      summary: Get list of sensors attached to a model
      parameters:
        - name: world_name
          in: path
          required: true
          schema:
            type: string
        - name: model_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of sensors retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorInfo'
        '404':
          description: Model or world not found

  /worlds/{world_name}/models/{model_name}/sensors/{sensor_type}:
    get:
      summary: Get sensor data from a specific sensor
      parameters:
        - name: world_name
          in: path
          required: true
          schema:
            type: string
        - name: model_name
          in: path
          required: true
          schema:
            type: string
        - name: sensor_type
          in: path
          required: true
          schema:
            type: string
            enum: [lidar, depth_camera, imu]
      responses:
        '200':
          description: Sensor data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
        '404':
          description: Sensor, model, or world not found

components:
  schemas:
    PhysicsProperties:
      type: object
      properties:
        gravity:
          type: array
          items:
            type: number
          description: Gravity vector [x, y, z]
          example: [0, 0, -9.8]
        max_step_size:
          type: number
          description: Maximum physics step size in seconds
          example: 0.001
        real_time_factor:
          type: number
          description: Target simulation speed relative to real time
          example: 1.0
        type:
          type: string
          description: Physics engine type
          example: "ode"
      required:
        - gravity
        - max_step_size
        - real_time_factor
        - type

    PhysicsPropertiesUpdate:
      type: object
      properties:
        gravity:
          type: array
          items:
            type: number
          description: New gravity vector [x, y, z]
        max_step_size:
          type: number
          description: New maximum physics step size in seconds
        real_time_factor:
          type: number
          description: New target simulation speed relative to real time

    SensorInfo:
      type: object
      properties:
        name:
          type: string
          description: Unique sensor identifier
        type:
          type: string
          enum: [lidar, depth_camera, imu]
          description: Type of sensor
        position:
          type: array
          items:
            type: number
          description: Position relative to model [x, y, z]
          example: [0, 0, 0.5]
        orientation:
          type: array
          items:
            type: number
          description: Orientation as quaternion [x, y, z, w]
          example: [0, 0, 0, 1]
      required:
        - name
        - type
        - position
        - orientation

    SensorData:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: When the data was captured
        sensor_name:
          type: string
          description: Name of the sensor that generated the data
        data:
          type: object
          description: Sensor-specific data payload
      required:
        - timestamp
        - sensor_name
        - data

    LidarData:
      allOf:
        - $ref: '#/components/schemas/SensorData'
        - type: object
          properties:
            data:
              type: object
              properties:
                ranges:
                  type: array
                  items:
                    type: number
                  description: Distance measurements in meters
                resolution:
                  type: number
                  description: Angular resolution in radians
                min_angle:
                  type: number
                  description: Minimum angle of scan in radians
                max_angle:
                  type: number
                  description: Maximum angle of scan in radians
          required:
            - data

    DepthCameraData:
      allOf:
        - $ref: '#/components/schemas/SensorData'
        - type: object
          properties:
            data:
              type: object
              properties:
                depth_image:
                  type: string
                  format: byte
                  description: Base64 encoded depth image
                color_image:
                  type: string
                  format: byte
                  description: Base64 encoded color image (optional)
                width:
                  type: integer
                  description: Image width in pixels
                height:
                  type: integer
                  description: Image height in pixels
                focal_length:
                  type: number
                  description: Camera focal length
          required:
            - data
            - width
            - height

    ImuData:
      allOf:
        - $ref: '#/components/schemas/SensorData'
        - type: object
          properties:
            data:
              type: object
              properties:
                linear_acceleration:
                  type: array
                  items:
                    type: number
                  description: Linear acceleration [x, y, z] in m/s²
                  example: [0.1, 0.05, -9.75]
                angular_velocity:
                  type: array
                  items:
                    type: number
                  description: Angular velocity [x, y, z] in rad/s
                  example: [0.01, 0.02, 0.0]
                orientation:
                  type: array
                  items:
                    type: number
                  description: Orientation as quaternion [x, y, z, w]
                  example: [0, 0, 0, 1]
          required:
            - data